### ISSUE TITLE
asking about my lidar

### ISSUE THREAD

**Issue by ErroujiOussama** [kaiaai/LDS#7]
![my lidar](https://github.com/user-attachments/assets/9a5d65ae-b9fd-433f-90b8-3a4c32be4c3f)
I have this lidar and I want to know how to use it with this library (wish version) the only information I know is that the lidar works with 115200 baud rate.
if you can help pls,
thank you.

**Comment by kaiaai** [comment]
Please check https://github.com/kaiaai/awesome-2d-lidars to identify your LiDAR. Compare your LiDAR to the published photos carefully. It might be a 3irobotix Delta-2A.

Once you have a good guess about your LiDAR model, look at the library examples under the `/examples` folder. Import the right header file. For Delta-2A that runs at 115200 baud the include is `#include LDS_DELTA_2A_115200.h' Read the source code to understand how that LiDAR model works  and which GPIO it requires. For a full example using all supported LiDAR models see https://github.com/kaiaai/firmware sketch in the kaiaai-esp32 folder.

**Comment by ErroujiOussama** [comment]
is that working with esp8266 or arduino (mega&uno), cause I don't have the esp32?

**Comment by kaiaai** [comment]
I have only tested it with ESP32.

**Comment by ErroujiOussama** [comment]
ok, do you have a simple program to just test the lidar and read the data from it, also display it using an interface. send me all resources do you have aboutthis topic pls. 
thank you :).

**Comment by kaiaai** [comment]
Please use the sample sketches in the 'examples' folder to run a Lidar and
print out its readings.
