### ISSUE TITLE
lidar sensor noise

### ISSUE THREAD

**Issue by hyunjun1234** [kaiaai/LDS#9]
I use ydlidar x3 pro. So, I did upload your .ino code "ydlidar_x4_pro_esp32".
But,  distance is 0. It is very big noise on the autonomous system.
Is there any solution?

**Comment by kaiaai** [comment]
Hello,
  Lidar noise is usually removed by examining multiple scans (rotations). Usually, robot mapping and localization software (ROS2 Nav2, Google Cartographer, etc.) takes care of this "denoise" automatically. If you are not using ROS, try comparing consecutive scans to detect missing distances - and try Googling Lidar processing.

**Comment by kaiaai** [comment]
Closing since LiDAR noise is not a library issue
